// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MissionMVCApp.Models;

namespace MissionMVCApp.Migrations
{
    [DbContext(typeof(MovieInfoContext))]
    [Migration("20220127000740_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("MissionMVCApp.Models.AddMovieSubmission", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<ushort>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Family",
                            Director = "Brenda Chapman and Mark Andrews",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG",
                            Title = "Brave",
                            Year = (ushort)2012
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Family",
                            Director = "Nathan Greno and Byron Howard",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG",
                            Title = "Tangled",
                            Year = (ushort)2010
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Comedy",
                            Director = "Jessica Bendinger",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG13",
                            Title = "Stick It",
                            Year = (ushort)2006
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
